# Generated by Django 4.2.1 on 2023-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_picter',
            field=models.ImageField(default='download.png', upload_to=''),
        ),
    ]
