# Generated by Django 4.2.1 on 2023-05-21 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_book_picter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
